apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv-volume
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/nginx"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pv-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx-pv-pod
  namespace: Ganesh Ghube
  livenessProbe:
    initialDelaySeconds: 1


spec:
  containers:
    - name: nginx-container
      imagePullPolicy: Always
      image: ganeshghube23/nginx:v8
      ports:
        - containerPort: 80
          name: "http-server"
      resources:
        requests:
          cpu: "500m"
          memory: "128Mi"
        limits:
          cpu: "1000m"
          memory: "256Mi"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: nginx-storage
      securityContext:
          allowPrivilegeEscalation: false
          capabilities:
                  drop:
                    - NET_RAW
                    - ALL

  volumes:
    - name: nginx-storage
      persistentVolumeClaim:
        claimName: nginx-pv-claim
